### ISSUE TITLE
If OD is too high beatmap breaks

### ISSUE THREAD

**Issue by Hololm** [FunOrange/osu-trainer#29]
Seems to be when OD is set > 10.0. When this happens, the beatmap becomes slowed down instead of sped up.

**Comment by tematikkp** [comment]
that means you need to use DT in that map

**Comment by Hololm** [comment]
rate could be less than 1.5x and OD still breaks, so it's not an issue with just using DT.

**Comment by ItzNico** [comment]
No, that is completely because nomod/HR mapvalues go up to AR10 & OD10 (And HP as well? idk nobody really cares about HP), if you want to go any higher you need to use DT, hence why osutrainer slows down the song so that when you add DT to it, you will get the BPM you used in the trainer
